# Access
CELERYD_USER="root"
CELERYD_GROUP="www-data"

# Path to directory and task
CELERY_BIN="/home/tresor/.virtualenvs/sigcdd_project/.venv/bin/celery"

CELERY_APP="sigcdd"

# Worker settings
CELERYD_NODES="workersbts"
CELERYD_OPTS=" --purge"

CELERYD_MULTI="multi"
CELERYD_STATE_DIR="/var/run/celery"
CELERYD_PID_FILE="/var/run/celery/%n.pid"
CELERYD_LOG_FILE="/var/log/celery/%n.log"

# Beat settings
CELERYBEAT_STATE_DIR="/var/run/celerybeat"
CELERYBEAT_PID_FILE="/var/run/celerybeat/beat.pid"
CELERYBEAT_LOG_FILE="/var/log/celery/beatsbts.log"
CELERYBEAT_SCHEDULE="/var/run/celerybeat/schedule"
CELERYBEAT_WORKDIR="/home/tresor/.virtualenvs/sigcdd_project/sigcdd/"

# INFO / DEBUG / etc
CELERYD_LOG_LEVEL="INFO"
CELERYBEAT_LOG_LEVEL="INFO"
