"""
Django settings for sigcdd project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import environ
ROOT_DIR = os.path.dirname(os.path.dirname(__file__))


env = environ.Env()
READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)
if READ_DOT_ENV_FILE:
	DOT_ENV_DIR = "{}/.envs".format(str(BASE_DIR.parent),)
	# OS environment variables take precedence over variables from .env
	env.read_env("{}/.django".format(DOT_ENV_DIR,))
	env.read_env("{}/.postgres".format(DOT_ENV_DIR,))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", False)
SECRET_KEY = env("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["example.com"])
INTERNAL_IPS = env.list("DJANNGO_INTERNAL_IPS")
TEMPLATE_DEBUG = DEBUG

SITE_ROOT = os.path.dirname(ROOT_DIR)


# Application definition

DJANGO_APPS = [
	"admin_interface",
    "colorfield",
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
    'django.contrib.humanize',
	'django.contrib.sites',
]

THIRD_PARTY_APPS = [
	'crispy_forms',  # Form layouts
	'allauth',  # registration
	"allauth.mfa",
	'allauth.account',  # registration
	'allauth.socialaccount',  # registration
	'mptt',
	'django_otp',
	'django_otp.plugins.otp_totp',
	'django_otp.plugins.otp_hotp',
	'django_otp.plugins.otp_static',
	'reversion',
	'django_celery_results',
	'django_celery_beat',
	'django_tables2',
	'django_filters',
	'bootstrap4',
	'guardian',
	'django_countries',
	"corsheaders",
	'oauth2_provider',
	'drf_yasg',
	'axes',
	'easy_thumbnails',
	'jsignature',
	'djmoney',
	'qr_code',
	'django_htmx',
	'import_export',
	'notifications',
	'bootstrap_modal_forms',
	'widget_tweaks',
	'django_extensions'
]

# Apps specific for this project go here.
LOCAL_APPS = [
	"users",
	"helpers",
	"core",
	"bankcheck",
	"cddaccount"
]

# See: https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django_session_timeout.middleware.SessionTimeoutMiddleware',
	'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Configure the django-otp package. Note this must be after the
    # AuthenticationMiddleware.
    "django_otp.middleware.OTPMiddleware",
    # Reset login flow middleware. If this middleware is included, the login
    # flow is reset if another page is loaded between login and successfully
    # entering two-factor credentials.
    #"allauth_2fa.middleware.AllauthTwoFactorMiddleware",
	"allauth.account.middleware.AccountMiddleware",
    "axes.middleware.AxesMiddleware",
	"users.middleware.EnableFirstLoginCPWMiddleWare",
	"users.middleware.SelectCddAccountWMiddleWare",

	"django_htmx.middleware.HtmxMiddleware",
	#'corsheaders.middleware.CorsMiddleware',

	'core.middleware.MaintenanceModeMiddleware',
	"users.middleware.Force2FAMiddleware",

]

ROOT_URLCONF = 'sigcdd.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.normpath(os.path.join(SITE_ROOT, 'templates'))],

		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.template.context_processors.i18n',
				'django.template.context_processors.media',
				'django.template.context_processors.static',
				'django.template.context_processors.tz',
				'django.contrib.messages.context_processors.messages',

			],
			'debug': DEBUG,
			'loaders': [
				'django.template.loaders.filesystem.Loader',
				'django.template.loaders.app_directories.Loader',
			],
		},
	},
]

TEMPLATES[0]['OPTIONS']['debug'] = DEBUG

WSGI_APPLICATION = 'sigcdd.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": env("SQL_ENGINE"),
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}



# PASSWORD STORAGE SETTINGS
# ------------------------------------------------------------------------------
# See https://docs.djangoproject.com/en/dev/topics/auth/passwords/#using-argon2-with-django


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# See: https://docs.djangoproject.com/en/dev/ref/settings/#site-id
SITE_ID = 1

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# directory that will host po and mo files
LOCALE_PATHS = (
	os.path.normpath(os.path.join(SITE_ROOT, 'locale')),

)
from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ( 'en', _('English') ),
    ( 'fr', _('French') ),
]


STATIC_ROOT =env("SIGCCD_STATIC_ROOT", default=os.path.normpath(os.path.join(SITE_ROOT, 'assets')))
# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = (
	os.path.normpath(os.path.join(SITE_ROOT, 'static')),
)

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = (
	'django.contrib.staticfiles.finders.FileSystemFinder',
	'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# MEDIA CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-root
# MEDIA_ROOT = str(APPS_DIR('media'))

MEDIA_ROOT = env("SIGCDD_MEDIA_ROOT",default=os.path.normpath(os.path.join(SITE_ROOT, 'media')))
# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = '/media/'




# AUTHENTICATION CONFIGURATION
# ------------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
)
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model
AUTH_USER_MODEL = "users.User"
ANONYMOUS_USERNAME = 'AnonymousUser'
# https://docs.djangoproject.com/en/dev/ref/settings/#login-redirect-url
LOGIN_REDIRECT_URL = "users:redirect"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-url
LOGIN_URL = "account_login"
LOGOUT_URL="account_logout"
#django guadian optionnel settings
ANONYMOUS_USER_ID = 0
GUARDIAN_RENDER_403 = True



# FIXTURES
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#fixture-dirs

FIXTURE_DIRS= os.path.normpath(os.path.join(SITE_ROOT, 'fixtures')),

# SECURITY
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-httponly
SESSION_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-browser-xss-filter
SECURE_BROWSER_XSS_FILTER = True
# https://docs.djangoproject.com/en/dev/ref/settings/#x-frame-options
X_FRAME_OPTIONS = "DENY"



DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap4.html"


###################### REDIS SETTINGS  ######################
REDIS_HOST = env("REDIS_HOST")
REDIS_PORT = env("REDIS_PORT")
REDIS_DB =env("REDIS_DB")
###################### END REDIS SETTINGS

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_REDIS_HOST = REDIS_HOST
SESSION_REDIS_PORT = REDIS_PORT
SESSION_REDIS_DB = REDIS_DB

CACHE_MIDDLEWARE_SECONDS = 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60*60

PLAN_DEFAULT_GRACE_PERIOD = 0

########## CELERY

CELERY_BEAT_SCHEDULER="django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_URL = env("CELERY_BROKER", default="redis://127.0.0.1:6379/1")
CELERY_RESULT_BACKEND = env("CELERY_BACKEND", default="redis://127.0.0.1:6379/1")


# CACHES
# ------------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL",default= "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Mimicing memcache behavior.
            # https://github.com/jazzband/django-redis#memcached-exceptions-behavior
            "IGNORE_EXCEPTIONS": True,
        },
    }
}


# Number of seconds of inactivity before a user is marked offline
USER_ONLINE_TIMEOUT = 300

# Number of seconds that we will keep track of inactive users for before
# their last seen is removed from the cache
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7
AXES_FAILURE_LIMIT=4
from datetime import timedelta
AXES_COOLOFF_TIME = timedelta(minutes=3)
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True

SUCCESS="success"

# django-allauth
# ------------------------------------------------------------------------------
ACCOUNT_ALLOW_REGISTRATION = False
SOCIALACCOUNT_AUTO_SIGNUP = False
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_AUTHENTICATION_METHOD = "username"
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_EMAIL_REQUIRED = True
# https://django-allauth.readthedocs.io/en/latest/configuration.html
#ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_ADAPTER = "users.adapters.AccountAdapter"
# https://django-allauth.readthedocs.io/en/latest/forms.html
ACCOUNT_FORMS = {"signup": "users.forms.UserSignupForm"}
# https://django-allauth.readthedocs.io/en/latest/configuration.html
SOCIALACCOUNT_ADAPTER = "users.adapters.SocialAccountAdapter"
# https://django-allauth.readthedocs.io/en/latest/forms.html
SOCIALACCOUNT_FORMS = {"signup": "users.forms.UserSocialSignupForm"}

#django money
CURRENCIES = ('XOF',)
CURRENCY_CHOICES = [('XOF', 'F CFA')]

FIRST_LOGIN_MODE=True
FIRST_LOGIN_MODE_REDIRECT_URL="account_change_password"



#USE_THOUSAND_SEPARATOR=True

DEFAULT_FROM_EMAIL=env("DEFAULT_FROM_EMAIL")
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_PORT = env.int("EMAIL_PORT")


from django.contrib import messages
MESSAGE_TAGS = {
    messages.DEBUG: "bg-light",
    messages.INFO: "text-white bg-primary",
    messages.SUCCESS: "text-white bg-success",
    messages.WARNING: "text-dark bg-warning",
    messages.ERROR: "text-white bg-danger",
}


RETURN_URL=None




OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}


if DEBUG:
	SWAGGER_SETTINGS = {
		'USE_SESSION_AUTH': False,
		'SECURITY_DEFINITIONS': {
			'Bearer': {
				'type': 'apiKey',
				'name': 'Authorization',
				'in': 'header'
			},
			'Aster API - Swagger': {
				'type': 'oauth2',
				'authorizationUrl': '/o/authorize',
				'tokenUrl': '/o/token/',
				'flow': 'application',
				'scopes': {
					'read groups': 'read groups',
				}
			}
		}

	}
DJANGO_CELERY_BEAT_TZ_AWARE=True

ASTER_VARIANTS = {
    'default': ('cddaccount.processors.dummy.DummyProvider', {}),
    'api': ('cddaccount.processors.api.ApiProvider', {})
}

ASTER_VARIANT_ACTIVE="default"


NOTIFICATIONS_NOTIFICATION_MODEL = 'helpers.Notification'



if not DEBUG:
	import sentry_sdk
	from sentry_sdk.integrations.django import DjangoIntegration

	sentry_sdk.init(
	    dsn= env("SENTRY_DSN",default="https://c16d28089ffa4efd8d4609cc6d7e94e1@o4504649641820160.ingest.sentry.io/4504649644965888"),
	    integrations=[
	        DjangoIntegration(),
	    ],

	    # Set traces_sample_rate to 1.0 to capture 100%
	    # of transactions for performance monitoring.
	    # We recommend adjusting this value in production.
	    traces_sample_rate=0.5,

	    # If you wish to associate users to errors (assuming you are using
	    # django.contrib.auth) you may enable sending PII data.
	    send_default_pii=True
	)



from logging.handlers import SysLogHandler

U_LOGFILE_NAME = env("LOGFILE")
U_LOGFILE_SIZE = 1 * 1024*1024
U_LOGFILE_COUNT = 1
U_LOGFILE_APP = 'sigcdd'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },

        'special': {
            '()': 'sigcdd.jsonLogger.SensitiveDataFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'
        },
        'json': {'()': "sigcdd.jsonLogger.CustomisedJSONFormatter"},
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'syslog': {
            'level': 'DEBUG',
            'class': 'logging.handlers.SysLogHandler',
            'formatter': 'verbose',
            'facility': SysLogHandler.LOG_LOCAL2,
        },
        'logfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': U_LOGFILE_NAME,
            'when':'midnight',
            'filters': ['special',],
            'formatter': 'json'

        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'api': {
            'handlers': ['logfile'],
            'level': 'DEBUG',
            'propagate': True,
        },
		'cddaccount': {
		            'handlers': ['logfile'],
		            'level': 'DEBUG',
		            'propagate': True,
		        },
		'bankcheck': {
		            'handlers': ['logfile'],
		            'level': 'DEBUG',
		            'propagate': True,
		        },
		'core': {
		            'handlers': ['logfile'],
		            'level': 'DEBUG',
		            'propagate': True,
		        },

    }
}


X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]
VIEW_CONSOLIDATION="VIEW_CONSOLIDATION"
TRESOR_ACCOUNT_SID=env("TRESOR_ACCOUNT_SID")
TRESOR_TOKEN=env("TRESOR_TOKEN")
TRESOR_GATEWAY_URL=env("TRESOR_GATEWAY_URL")

MAINTENANCE_MODE = env.int("MAINTENANCE_MODE",0)

SESSION_EXPIRE_SECONDS=600  # 10 min
SESSION_EXPIRE_AFTER_LAST_ACTIVITY=True
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
SESSION_TIMEOUT_REDIRECT='/accounts/login/'
PAYMENT_USES_SSL=env.bool("PAYMENT_USES_SSL")



EPAIEMENT_BASE_URL=env("EPAIEMENT_BASE_URL")
EPAIEMENT_USERNAME=env("EPAIEMENT_USERNAME")
EPAIEMENT_PASSWORD=env("EPAIEMENT_PASSWORD")
EPAIEMENT_APPCODE=env("EPAIEMENT_APPCODE")



EPAIEMENT_X_USER_ID=env("EPAIEMENT_X_USER_ID")
EPAIEMENT_CLIENT_ID=env("EPAIEMENT_CLIENT_ID")
EPAIEMENT_CLIENT_SECRET=env("EPAIEMENT_CLIENT_SECRET")



#ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter'
ACCOUNT_ADAPTER = 'users.adapters.SMSOTPAdapter'
ACTIVATE_TOPT_SMS=False

FORCE_2FA_ENABLED = env.bool("FORCE_2FA_ENABLED", default=False)

MFA_TOTP_ACTIVATE_REAUTH_REQUIRED = False
MFA_ADAPTER = "users.adapters.CustomMFAAdapter"

ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']  # ← nouveau
SOCIALACCOUNT_ONLY = False
MFA_TOTP_ISSUER = "SIGCDD"
MFA_ENFORCE_AUTHENTICATION = False